[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Zukitwo-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human
Comment=A simple grey theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Zukitwo-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human
MetacityTheme=Zukitwo-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human-Human
ButtonLayout=:minimize,maximize,close
