[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Zukitwo-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious
Comment=A simple grey theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Zukitwo-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious
MetacityTheme=Zukitwo-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious-Illustrious
ButtonLayout=:minimize,maximize,close
