[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Zukitwo-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave
Comment=A simple grey theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Zukitwo-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave
MetacityTheme=Zukitwo-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave-Brave
ButtonLayout=:minimize,maximize,close
