[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Zukitwo-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble
Comment=A simple grey theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Zukitwo-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble
MetacityTheme=Zukitwo-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble-Noble
ButtonLayout=:minimize,maximize,close
